apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapiont
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapiont
  template:
    metadata:
      labels:
        app: sapiont
    spec:
      containers:
      - image: okteto.dev/sapiont:latest
        name: sapiont
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "animefrenzy.net"
        - name: Vless_UUID
          value: "2d4400a5-e594-4c2f-b64e-700b0096c3cc"
        - name: Vless_Path
          value: "/aOYFert56"
        - name: Vmess_UUID
          value: "2d4400a5-e594-4c2f-b64e-700b0096c3cc"
        - name: Vmess_Path
          value: "/herc06y"
        - name: Share_Path
          value: "/Share134"
