apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeroil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yeroil
  template:
    metadata:
      labels:
        app: yeroil
    spec:
      containers:
      - image: okteto.dev/yeroil:latest
        name: yeroil
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "animeflick.net"
        - name: Vless_UUID
          value: "ab76eb97-fb02-4cef-adc4-4bc10f30b4a5"
        - name: Vless_Path
          value: "/REcvt54"
        - name: Vmess_UUID
          value: "ab76eb97-fb02-4cef-adc4-4bc10f30b4a5"
        - name: Vmess_Path
          value: "/ADCF676R"
        - name: Share_Path
          value: "/Share323"
