apiVersion: apps/v1
kind: Deployment
metadata:
  name: giolre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giolre
  template:
    metadata:
      labels:
        app: giolre
    spec:
      containers:
      - image: okteto.dev/giolre:latest
        name: giolre
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "7b9a7cfc-c286-4961-b731-6a187535196b"
        - name: Vless_Path
          value: "/airedc0"
        - name: Vmess_UUID
          value: "7b9a7cfc-c286-4961-b731-6a187535196b"
        - name: Vmess_Path
          value: "/ilecraz"
        - name: Share_Path
          value: "/Share731"
