apiVersion: apps/v1
kind: Deployment
metadata:
  name: peaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peaction
  template:
    metadata:
      labels:
        app: peaction
    spec:
      containers:
      - image: okteto.dev/peaction:latest
        name: peaction
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "kissanime.ru.net"
        - name: Vless_UUID
          value: "c53a1931-8b30-40c8-945d-e94c23808616"
        - name: Vless_Path
          value: "/DFGil7df"
        - name: Vmess_UUID
          value: "c53a1931-8b30-40c8-945d-e94c23808616"
        - name: Vmess_Path
          value: "/giouwt"
        - name: Share_Path
          value: "/Share324"
