apiVersion: apps/v1
kind: Deployment
metadata:
  name: action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: action
  template:
    metadata:
      labels:
        app: action
    spec:
      containers:
      - image: okteto.dev/action:latest
        name: action
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.moviecrumbs.net"
        - name: Vless_UUID
          value: "f67fcce4-40a7-4af7-aa07-366618a7fc84"
        - name: Vless_Path
          value: "/TYsedu5"
        - name: Vmess_UUID
          value: "f67fcce4-40a7-4af7-aa07-366618a7fc84"
        - name: Vmess_Path
          value: "/YISFCR76"
        - name: Share_Path
          value: "/Share512"
